update deprecated call to distplot and gca in _for_slides folder (#2)
1) distplot is replaced with histplot with 2 parameters (, kde=True, stat=\"density\") as suggested in https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751
2) gca changed to subplot as suggested in https://stackoverflow.com/questions/76047803/typeerror-figurebase-gca-got-an-unexpected-keyword-argument-projection
Note: using gca was giving the following error in the notebook: TypeError: FigureBase.gca() got an unexpected keyword argument 'projection'

Co-authored-by: gakamath <Ganesh.Kamath@amd.com>